### ISSUE TITLE
Measure anisotropic stress

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/napari-stress#106]
The anisotropic stress at every (quadrature) point can be calculated as shown in the code [here](https://github.com/campaslab/STRESS/blob/29c6627cb4c95330567cde5d0189238e3b95d7ab/Refactored_Droplet_Class.py#L947):

```python
# This is the 2\gamma*(H-H0 we USE FOR OUR anisotropic stress analysis:
self.Anis_Stress_pts_lbdv = self.TwoGammaVal*(self.Mean_Curv_lbdv_pts - self.H0_Int_of_H_over_Area) 	
```

Here, the variable `TwoGammaVal`  (2$\gamma$) is a physical property of the experiment as described in the [paper ](https://www.biorxiv.org/content/10.1101/2021.03.26.437148v1.full) (Materials&Methods > Tissue-scale stresses). It needs to be given by the user as a (`float`) parameter.

This function should go into `src/napari_stress/_measurements/stresses.py`.

**Comment by jo-mueller** [comment]
Issue #110 needs to be fixed before this can move forward.

**Comment by jo-mueller** [comment]
@GrossBJ how's it going? I'd have a minor question about something related to the stress code (rather minor) I can't quite wrap my head around: In the originial stress code (here), the maximal tissue stress anisotropy is calculated as follows:

```python
# Calculate 2\gamma*(H_3 - H_1), mirroring Ellipsoid max stress anisotropy:
Avg_H_lbdv_X_axis = (self.Mean_Curv_lbdv_pts[0,0] + self.Mean_Curv_lbdv_pts[1,0])/2.	
Avg_H_lbdv_Y_axis = (self.Mean_Curv_lbdv_pts[2,0] + self.Mean_Curv_lbdv_pts[3,0])/2.							
Avg_H_lbdv_Z_axis = (self.Mean_Curv_lbdv_pts[4,0] + self.Mean_Curv_lbdv_pts[5,0])/2.

self.Anis_Stress_Drop_Ellips_e1_e3_Axes = self.TwoGammaVal*np.sum(np.multiply(self.Maj_Min_Axis, np.array([ Avg_H_lbdv_X_axis, Avg_H_lbdv_Y_axis, Avg_H_lbdv_Z_axis ])))
```

whereas `self.Mean_Curv_lbdv_pts` should be the curvature at every quadrature point, `self.Maj_Min_Axis` is of form `[1, -1, -1]` if the first axis is the major axis of the ellipsoid.

Now...what exactly is the significance of particularly the first 6 curvature values (i.e., `Mean_Curv_lbdv_pts[0:5]`) among all the curvatures? According to the paper this should probably reflect this section:

![Capture](https://user-images.githubusercontent.com/38459088/186708984-0034b824-a90b-4ac4-a92b-e3a969c723e9.PNG)

Thanks in advance for your help!

**Comment by GrossBJ** [comment]
Hi Johannes,
To be honest I'm not sure, since a lot of things I wrote were based on specific comments someone in the lab may have made (even in passing). I would probably need to see how it was used in the main file to guess why I did that. 
Thanks,Ben

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 25, 2022 at 17:39, Johannes ***@***.***> wrote:   


@GrossBJ how's it going? I'd have a minor question about something related to the stress code (rather minor) I can't quite wrap my head around: In the originial stress code (here), the maximal tissue stress anisotropy is calculated as follows:
# Calculate 2\gamma*(H_3 - H_1), mirroring Ellipsoid max stress anisotropy:
Avg_H_lbdv_X_axis = (self.Mean_Curv_lbdv_pts[0,0] + self.Mean_Curv_lbdv_pts[1,0])/2.	
Avg_H_lbdv_Y_axis = (self.Mean_Curv_lbdv_pts[2,0] + self.Mean_Curv_lbdv_pts[3,0])/2.							
Avg_H_lbdv_Z_axis = (self.Mean_Curv_lbdv_pts[4,0] + self.Mean_Curv_lbdv_pts[5,0])/2.

self.Anis_Stress_Drop_Ellips_e1_e3_Axes = self.TwoGammaVal*np.sum(np.multiply(self.Maj_Min_Axis, np.array([ Avg_H_lbdv_X_axis, Avg_H_lbdv_Y_axis, Avg_H_lbdv_Z_axis ])))
whereas self.Mean_Curv_lbdv_pts should be the curvature at every quadrature point, self.Maj_Min_Axis is of form [1, -1, -1] if the first axis is the major axis of the ellipsoid.

Now...what exactly is the significance of particularly the first 6 curvature values (i.e., Mean_Curv_lbdv_pts[0:5]) among all the curvatures? According to the paper this should probably reflect this section:



Thanks in advance for your help!

**Comment by jo-mueller** [comment]
Hi @GrossBJ , sorry, I forgot to put the link to the [location in the original code](https://github.com/campaslab/STRESS/blob/29c6627cb4c95330567cde5d0189238e3b95d7ab/Refactored_Droplet_Class.py#L1015)

**Comment by GrossBJ** [comment]
Ah now I see, thanks!
Because the ellipsoidal coordinates are always along the major x, y, z axes we can use the fact that the first 6 lebedev points are along each of these axes to immediately get the mean curvatures there. Anotherwards we don't need to do any interpolation because the points we are interested in are perfectly aligned with the axes.
Hope this helps!-Ben

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 26, 2022 at 11:33, Johannes ***@***.***> wrote:   


Hi @GrossBJ , sorry, I forgot to put the link to the location in the original code

**Comment by jo-mueller** [comment]
> we can use the fact that the first 6 lebedev points are along each of these axes

Ok cool, that wasn't quite evident from the code :) I implemented this measurement by using the formula for the [mean curvature on the ellipsoid](https://github.com/campaslab/STRESS/blob/29c6627cb4c95330567cde5d0189238e3b95d7ab/Refactored_Droplet_Class.py#L217) on the points that are at the tips of the major axes of the ellipsoid, which should be equivalent, right?

**Comment by GrossBJ** [comment]
Yep! For an ellipsoid it is very simple to calculate! It should give the same answer, but there are many different ways of writing it.

Sent from Yahoo Mail on Android 
 
  On Fri, Sep 2, 2022 at 15:47, Johannes ***@***.***> wrote:   



we can use the fact that the first 6 lebedev points are along each of these axes


Ok cool, that wasn't quite evident from the code :) I implemented this measurement by using the formula for the mean curvature on the ellipsoid on the points that are at the tips of the major axes of the ellipsoid, which should be equivalent, right?

**Comment by jo-mueller** [comment]
Awesome @GrossBJ , I'll close this then 💯
